### ISSUE TITLE
Change Application Type

### ISSUE THREAD

**Issue by bkacmaz** [balena-io/balena-sdk#1190] opened 2022-01-27 08:56 UTC
## Actual Behavior

When I create my fleets in balena-CLI, my application type output is like given below,
<img width="290" alt="image" src="https://user-images.githubusercontent.com/85884332/151324965-abe4301d-7aaf-4195-878f-29385813af5d.png">

But, when I create my fleets in dashboard, my application type output is like given below,
<img width="472" alt="image" src="https://user-images.githubusercontent.com/85884332/151324988-47ce302b-d5a4-49be-a5b9-6de93becc22a.png">

What does the application type depend on and how can I change application type?

## Specifications
- Node version: v12.22.9
- Npm version: 6.14.15

**Comment by bkacmaz** [comment] 2022-01-27 11:21
https://forums.balena.io/t/change-application-type/351122/3

**Comment by thgreasi** [comment] 2022-01-27 11:35
Hi,
As far as I can read from the forums thread, it seems that your balena-cli is pointed to an openBalena instance.
Is that right?
That's an expected behavior for openBalena since the "default" application type is the only one that openBalena offers, which includes all features that openBalena supports.

Is this affecting you in some way?

**Comment by bkacmaz** [comment] 2022-01-27 11:52
Actually, I just want to create public url in open balena server. :)

**Comment by thgreasi** [comment] 2022-01-27 15:46
That's unfortunately not supported by open-balena @bkacmaz .
Is there anything else we can help in this issue or should we close it?

**Comment by thgreasi** [comment] 2022-02-04 12:13
Closing since this seems to be answered.
Feel free to re-open if this is causing any issue for you.

**Closed by thgreasi** 2022-02-04 12:13 UTC
